In [1]:
# problem statement --> to crete a website where user inputs a movie name and we have to give top 5 similar movies

In [2]:
import numpy as np
import pandas as pd

C:\Users\manjh\AppData\Local\Temp\ipykernel_21428\1662815981.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [4]:
 movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [7]:
credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

In [8]:
movies.merge(credits, on='title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [9]:
movies.merge(credits, on='title').shape

(4809, 23)

In [10]:
movies.shape

(4803, 20)

In [11]:
credits.shape

(4803, 4)

In [12]:
movies= movies.merge(credits, on='title')

In [13]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
# columns req:
# genres, id( to fetch movie posters later on), keywords, title( not originai_title coz it can be in regional lang also)
# overview, cast, crew
movies[['movie_id','title','overview','genres','keywords','cast','crew']]

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [15]:
#movies['original_language'].value_counts()

In [16]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [17]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
# Data Preprocessing-----------------------------------------------

movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [20]:
movies.dropna(inplace=True) # remove those three movies whose overview is not there
# dropna --> Remove all rows wit NULL values

In [21]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [22]:
movies.duplicated().sum() # check if any row is duplicate

0

In [23]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [24]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [25]:
# ['Action','Adventure','Fantasy','Science Fiction']
def convert(obj):
    L = []
    for i in ast.literal_eval(obj): # to convert string of list to list
       L.append(i['name'])
    return L

In [26]:
 movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [27]:
movies['genres']= movies['genres'].apply(convert)

In [28]:
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united statesâ€“mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [29]:
movies['keywords']=movies['keywords'].apply(convert)

In [30]:
# for cast col, extract top 3 dictionaries and from that only the actors name
def convert3(obj):
    L = []
    counter=0
    for i in ast.literal_eval(obj): # to convert string of list to list
        if counter != 3:
           L.append(i['name'])
           counter+=1
        else:
            break
    return L

In [31]:
movies['cast'].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, LÃ©a Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry BishÃ©, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [32]:
movies['cast']=movies['cast'].apply(convert3)

In [33]:
# from crew col, we only want the directors name
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director' :
            L.append(i['name'])
            break
    return L

In [34]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [35]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [36]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [37]:
# now convert overview col from string to list so it can be later concatenated with other cols
movies['overview'].apply(lambda x:x.split()) # we get list for every row

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [38]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [39]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [40]:
# now the entire dataset consists of cols with lists.
# next we will concatenate those list to produce a big list
# later we ll convert the list to string again so it ll be a big paragraph--- i.e tag

# for col 'genres', 'keywords','cast','crew'--> remove spaces btw words
# eg--> Sam Worthington (here 2 entities which ll create confusion) to SamWorthington ( here only one entitie)
movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [41]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [42]:
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [43]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [44]:
# now make a new col called tags where we ll concatenate all the cols
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [45]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [46]:
new_df = movies[['movie_id','title','tags']]

In [47]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [48]:
# now convert list back to strings in tags col
new_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bondâ€™s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [49]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\manjh\AppData\Local\Temp\ipykernel_21428\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [50]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [51]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [52]:
new_df['tags'].apply(lambda x:x.lower()) # converting to lowercase

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bondâ€™s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [53]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\manjh\AppData\Local\Temp\ipykernel_21428\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [54]:
new_df.head() # final preprocessed dataset

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [55]:
# ['loved','loving','love']
# after stemming --> ['love','love','love']
import nltk
from nltk.stem.porter import PorterStemmer

In [56]:
ps= PorterStemmer()

In [57]:
def stem(text):
    y = []
    for i in text.split():
       y.append(ps.stem(i))
    return " ".join(y)

In [58]:
ps.stem('loving')

'love'

In [59]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'
)

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [60]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [61]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\manjh\AppData\Local\Temp\ipykernel_21428\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [62]:
######################### VECTORIZATION ##########################################3
# similarity btw movies is on the basis of tags i.e similarity btw texts in the tags i.e common words btw them
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [63]:
new_df['tags'][1]

"captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems. adventur fantasi action ocean drugabus exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditssting johnnydepp orlandobloom keiraknightley goreverbinski"

In [64]:
# better approach is convert tags into vectors i.e text-->vectors process is known as text vectorization
# recommend closest vectors
# technique for text vectorization --> 'Bag of words'(using here}

# Bag of words :
# concatenate all tags i.e largeText= tag1+tag2+..............
# among the words in largeText find the top 5k most occurring words 
#            w1,w2,w3........w5000
# fr movie1: 5, 4 ,2,.......... ( no of times the words(w1,w2...) are occuring in movie1)
# fr movie2: 3, 5, 1...........
#....
#fr movie5k:....................
# table of (5000,5000) where each row here is known as vector
# if only 2 words then table of (5000,2) is in 2 dimensional space:
#            w1,w2
# fr movie1: 5, 4 (plot 5,4 in 2-dimensional space)
# fr movie2: 3, 5 (plot 3,5 in 2-dimensional space)
#....
#fr movie5k:.....

# we won't consider stopwords (eg->are,and,from,etc ; stopwords are used only for sentence formation) 
# so first remove stopwords & do vectorization on the rest 
# for this we ll use scikit learn --> inside scikit learn we have count vectorization that we ll use for this purpose

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [66]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [67]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [68]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [69]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [70]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [71]:
# in higher dimension euclidean dist is not a reliable measure so here we use cosine distance
# cosine dist--> angle btw the vectors , the more the diff btw those angles the more distant those movies are
from sklearn.metrics.pairwise import cosine_similarity # cosine similarity--> always btw 0 & 1

In [72]:
similarity=cosine_similarity(vectors)

In [73]:
similarity[0] # similarity of 1st movie wrt to every other movie

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [79]:
list(enumerate(similarity[0])) # we cant directly sort the similarities cox we ll loose the ref to which that similarity is for

[(0, 1.0000000000000002),
 (1, 0.08346223261119858),
 (2, 0.08603090020146065),
 (3, 0.0734718358370645),
 (4, 0.18929940971212042),
 (5, 0.10838874619051501),
 (6, 0.04024218182927669),
 (7, 0.14673479641335554),
 (8, 0.05923488777590923),
 (9, 0.0967301666813349),
 (10, 0.10259783520851541),
 (11, 0.09464970485606021),
 (12, 0.09037128496931669),
 (13, 0.04499212706658476),
 (14, 0.12824729401064427),
 (15, 0.06282808624375433),
 (16, 0.07894736842105264),
 (17, 0.13977653617040256),
 (18, 0.09493290614465533),
 (19, 0.0830812984794528),
 (20, 0.058038100008800934),
 (21, 0.10968169942141635),
 (22, 0.0662266178532522),
 (23, 0.08740748201220976),
 (24, 0.0533380747062665),
 (25, 0.05101627678885769),
 (26, 0.15389675281277312),
 (27, 0.18693292157876878),
 (28, 0.116543309349613),
 (29, 0.065033247714309),
 (30, 0.06684847767323797),
 (31, 0.15907119074394446),
 (32, 0.08520286456846099),
 (33, 0.09733285267845754),
 (34, 0.0),
 (35, 0.09933992677987831),
 (36, 0.17316974359835272),
 (37, 0.07894736842105264),
 (38, 0.08111071056538127),
 (39, 0.08226127456606226),
 (40, 0.07694837640638656),
 (41, 0.16563698349810535),
 (42, 0.0),
 (43, 0.09086217008485092),
 (44, 0.03382550457458692),
 (45, 0.08240856434303293),
 (46, 0.1391037210186643),
 (47, 0.19672236884115843),
 (48, 0.08447772061910234),
 (49, 0.0582716546748065),
 (50, 0.11295649894498103),
 (51, 0.08048436365855338),
 (52, 0.14843120879858804),
 (53, 0.042973504259354006),
 (54, 0.031219527052723135),
 (55, 0.07038153430777869),
 (56, 0.13834289277321493),
 (57, 0.024182541670333724),
 (58, 0.06748819059987714),
 (59, 0.07254762501100116),
 (60, 0.018367958959266125),
 (61, 0.23179316248638274),
 (62, 0.0837707816583391),
 (63, 0.08175191193132876),
 (64, 0.029617443887954616),
 (65, 0.019529164171612674),
 (66, 0.02249606353329238),
 (67, 0.16452254913212452),
 (68, 0.1204950466257556),
 (69, 0.02649064714130088),
 (70, 0.076004188790721),
 (71, 0.07336739820667779),
 (72, 0.13710212427677043),
 (73, 0.0331133089266261),
 (74, 0.20246457179963143),
 (75, 0.10390486669322622),
 (76, 0.07175473098524099),
 (77, 0.014394823400711486),
 (78, 0.050669459193814),
 (79, 0.0623109738595896),
 (80, 0.050464733268936676),
 (81, 0.11020775375559676),
 (82, 0.076004188790721),
 (83, 0.17996850826633903),
 (84, 0.12361284651454937),
 (85, 0.11412706387705432),
 (86, 0.07098727864204515),
 (87, 0.11128297681493143),
 (88, 0.09037128496931669),
 (89, 0.05757929360284594),
 (90, 0.06131393394849658),
 (91, 0.16692446522239718),
 (92, 0.0623109738595896),
 (93, 0.07098727864204515),
 (94, 0.1873171623163388),
 (95, 0.1404878717372541),
 (96, 0.07694837640638656),
 (97, 0.06952346619889824),
 (98, 0.07509392614826384),
 (99, 0.02666903735313325),
 (100, 0.06765100914917384),
 (101, 0.07694837640638656),
 (102, 0.12462194771917919),
 (103, 0.07987230638308718),
 (104, 0.05564148840746572),
 (105, 0.1037571695799112),
 (106, 0.0623109738595896),
 (107, 0.061806423257274694),
 (108, 0.14509525002200235),
 (109, 0.06488856845230502),
 (110, 0.04499212706658476),
 (111, 0.15018785229652767),
 (112, 0.07694837640638656),
 (113, 0.043355498476206004),
 (114, 0.04588314677411236),
 (115, 0.043747863925980714),
 (116, 0.04836508334066745),
 (117, 0.05923488777590923),
 (118, 0.03364315551262445),
 (119, 0.043355498476206004),
 (120, 0.0),
 (121, 0.11128297681493143),
 (122, 0.116543309349613),
 (123, 0.1124803176664619),
 (124, 0.06748819059987714),
 (125, 0.07843304784240032),
 (126, 0.13334518676566626),
 (127, 0.14601068654819693),
 (128, 0.0),
 (129, 0.09269795493186431),
 (130, 0.027036903521793755),
 (131, 0.10526315789473685),
 (132, 0.04499212706658476),
 (133, 0.028239124736245257),
 (134, 0.12977713690461004),
 (135, 0.0),
 (136, 0.023414645289542353),
 (137, 0.0301237616564389),
 (138, 0.12824729401064427),
 (139, 0.12072654548783007),
 (140, 0.04499212706658476),
 (141, 0.08740748201220976),
 (142, 0.08471737420873576),
 (143, 0.08671099695241201),
 (144, 0.05006261743217589),
 (145, 0.019252140716412975),
 (146, 0.016303866268150616),
 (147, 0.05564148840746572),
 (148, 0.09733285267845754),
 (149, 0.15511334686589626),
 (150, 0.16426202236672155),
 (151, 0.2029530274475215),
 (152, 0.08346223261119858),
 (153, 0.07868894753646337),
 (154, 0.06131393394849658),
 (155, 0.02043797798283219),
 (156, 0.05990422978731538),
 (157, 0.09933992677987831),
 (158, 0.13369695534647594),
 (159, 0.06362847629757779),
 (160, 0.11712303424679457),
 (161, 0.03181423814878889),
 (162, 0.0331133089266261),
 (163, 0.050669459193814),
 (164, 0.08000711205939975),
 (165, 0.04588314677411236),
 (166, 0.12515654358043973),
 (167, 0.09037128496931669),
 (168, 0.17521916101261562),
 (169, 0.08830215713766959),
 (170, 0.10650358071057624),
 (171, 0.02271554252121273),
 (172, 0.21239769762143662),
 (173, 0.023174488732966077),
 (174, 0.07792865001991967),
 (175, 0.07098727864204515),
 (176, 0.02913582733740325),
 (177, 0.0),
 (178, 0.024455799402225926),
 (179, 0.07254762501100116),
 (180, 0.022075539284417398),
 (181, 0.04499212706658476),
 (182, 0.11707322644771176),
 (183, 0.07038153430777869),
 (184, 0.177343107178349),
 (185, 0.050669459193814),
 (186, 0.05901671065234752),
 (187, 0.15389675281277312),
 (188, 0.022075539284417398),
 (189, 0.1147078669352809),
 (190, 0.08447772061910234),
 (191, 0.04891159880445185),
 (192, 0.047324852428030105),
 (193, 0.07878168645790681),
 (194, 0.0),
 (195, 0.05923488777590923),
 (196, 0.05195243334661311),
 (197, 0.036973693332326786),
 (198, 0.057353933467640436),
 (199, 0.08671099695241201),
 (200, 0.10882143751650175),
 (201, 0.0),
 (202, 0.031219527052723135),
 (203, 0.08346223261119858),
 (204, 0.04947706959952935),
 (205, 0.07443229275647868),
 (206, 0.11092107999698035),
 (207, 0.07694837640638656),
 (208, 0.12262786789699316),
 (209, 0.06765100914917384),
 (210, 0.07509392614826384),
 (211, 0.024455799402225926),
 (212, 0.06622661785325219),
 (213, 0.05901671065234752),
 (214, 0.0),
 (215, 0.06622661785325219),
 (216, 0.06488856845230502),
 (217, 0.08520286456846099),
 (218, 0.03823595564509363),
 (219, 0.09197090092274487),
 (220, 0.1777046633277277),
 (221, 0.047324852428030105),
 (222, 0.07987230638308718),
 (223, 0.10390486669322622),
 (224, 0.060833032924035954),
 (225, 0.046829290579084706),
 (226, 0.0301237616564389),
 (227, 0.08226127456606226),
 (228, 0.11037769642208699),
 (229, 0.1074861545850028),
 (230, 0.09183979479633063),
 (231, 0.0),
 (232, 0.11128297681493143),
 (233, 0.1037571695799112),
 (234, 0.08594700851870801),
 (235, 0.076004188790721),
 (236, 0.11470786693528087),
 (237, 0.0662266178532522),
 (238, 0.11092107999698035),
 (239, 0.09125667909262308),
 (240, 0.046829290579084706),
 (241, 0.07894736842105264),
 (242, 0.08111071056538127),
 (243, 0.09269795493186431),
 (244, 0.09197090092274487),
 (245, 0.08111071056538127),
 (246, 0.07594632491572426),
 (247, 0.0),
 (248, 0.04456565178215865),
 (249, 0.13834289277321493),
 (250, 0.0),
 (251, 0.04188539082916955),
 (252, 0.020277677641345318),
 (253, 0.06282808624375433),
 (254, 0.06952346619889824),
 (255, 0.0),
 (256, 0.11164843913471803),
 (257, 0.0533380747062665),
 (258, 0.01769980813511972),
 (259, 0.06131393394849658),
 (260, 0.20395079136182276),
 (261, 0.024182541670333724),
 (262, 0.10650358071057624),
 (263, 0.09733285267845754),
 (264, 0.0),
 (265, 0.02742042485535409),
 (266, 0.0989541391990587),
 (267, 0.06488856845230502),
 (268, 0.052631578947368425),
 (269, 0.029617443887954616),
 (270, 0.08830215713766959),
 (271, 0.07098727864204515),
 (272, 0.02782074420373286),
 (273, 0.021119430154775586),
 (274, 0.08977310580745099),
 (275, 0.1433848336691011),
 (276, 0.06243905410544627),
 (277, 0.053099424405359155),
 (278, 0.11707322644771176),
 (279, 0.09269795493186431),
 (280, 0.0),
 (281, 0.065033247714309),
 (282, 0.04456565178215865),
 (283, 0.02742042485535409),
 (284, 0.018367958959266125),
 (285, 0.019529164171612674),
 (286, 0.0781166566864507),
 (287, 0.025976216673306556),
 (288, 0.02742042485535409),
 (289, 0.04588314677411236),
 (290, 0.06362847629757779),
 (291, 0.05006261743217589),
 (292, 0.08885233166386385),
 (293, 0.029617443887954616),
 (294, 0.1433848336691011),
 (295, 0.10526315789473685),
 (296, 0.038778336716474064),
 (297, 0.044151078568834795),
 (298, 0.0),
 (299, 0.05945550264670635),
 (300, 0.1711905958155815),
 (301, 0.09365858115816939),
 (302, 0.06952346619889824),
 (303, 0.02782074420373286),
 (304, 0.06578947368421054),
 (305, 0.1900748713929803),
 (306, 0.08111071056538127),
 (307, 0.10876595882948199),
 (308, 0.06765100914917384),
 (309, 0.06243905410544627),
 (310, 0.03065696697424829),
 (311, 0.15018785229652765),
 (312, 0.10012523486435178),
 (313, 0.05484084971070818),
 (314, 0.0),
 (315, 0.08346223261119858),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.09933992677987831),
 (320, 0.03065696697424829),
 (321, 0.0),
 (322, 0.2105263157894737),
 (323, 0.029617443887954616),
 (324, 0.024455799402225926),
 (325, 0.09933992677987831),
 (326, 0.05647824947249051),
 (327, 0.027036903521793755),
 (328, 0.02742042485535409),
 (329, 0.07894736842105264),
 (330, 0.10012523486435178),
 (331, 0.08998425413316952),
 (332, 0.106676149412533),
 (333, 0.024455799402225926),
 (334, 0.0967301666813349),
 (335, 0.046348977465932154),
 (336, 0.06917144638660747),
 (337, 0.04543108504242546),
 (338, 0.0),
 (339, 0.04891159880445185),
 (340, 0.04947706959952935),
 (341, 0.08226127456606226),
 (342, 0.16122923187750418),
 (343, 0.019252140716412975),
 (344, 0.029617443887954616),
 (345, 0.02294157338705618),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06131393394849658),
 (349, 0.076004188790721),
 (350, 0.04891159880445185),
 (351, 0.0),
 (352, 0.02742042485535409),
 (353, 0.04120428217151646),
 (354, 0.021677749238103002),
 (355, 0.03650267163704923),
 (356, 0.09037128496931669),
 (357, 0.0),
 (358, 0.0602475233128778),
 (359, 0.031219527052723135),
 (360, 0.020942695414584774),
 (361, 0.07509392614826384),
 (362, 0.09544271444636668),
 (363, 0.09909250441117726),
 (364, 0.023414645289542353),
 (365, 0.07509392614826384),
 (366, 0.05647824947249051),
 (367, 0.0),
 (368, 0.12977713690461004),
 (369, 0.12824729401064427),
 (370, 0.050669459193814),
 (371, 0.09567297464698798),
 (372, 0.047324852428030105),
 (373, 0.17292861596651865),
 (374, 0.03797316245786213),
 (375, 0.061313933948496574),
 (376, 0.046829290579084706),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05073825686188038),
 (380, 0.05195243334661311),
 (381, 0.0837707816583391),
 (382, 0.0),
 (383, 0.043355498476206004),
 (384, 0.028676966733820218),
 (385, 0.0),
 (386, 0.021873931962990357),
 (387, 0.023662426214015053),
 (388, 0.0),
 (389, 0.08740748201220976),
 (390, 0.026315789473684213),
 (391, 0.056573571480353566),
 (392, 0.0301237616564389),
 (393, 0.0),
 (394, 0.024738534799764674),
 (395, 0.0533380747062665),
 (396, 0.043747863925980714),
 (397, 0.05195243334661311),
 (398, 0.0),
 (399, 0.023662426214015053),
 (400, 0.09037128496931669),
 (401, 0.031219527052723135),
 (402, 0.07792865001991967),
 (403, 0.0830812984794528),
 (404, 0.06131393394849658),
 (405, 0.05564148840746572),
 (406, 0.0207703246198632),
 (407, 0.021300716142115247),
 (408, 0.03244428422615251),
 (409, 0.0),
 (410, 0.0978231976089037),
 (411, 0.052631578947368425),
 (412, 0.09567297464698798),
 (413, 0.1411956236812263),
 (414, 0.029617443887954616),
 (415, 0.053418342734682205),
 (416, 0.050669459193814),
 (417, 0.03244428422615251),
 (418, 0.03539961627023944),
 (419, 0.06882472016116853),
 (420, 0.1124803176664619),
 (421, 0.023174488732966077),
 (422, 0.116543309349613),
 (423, 0.04120428217151646),
 (424, 0.03721614637823934),
 (425, 0.06390214842634574),
 (426, 0.05374307729250139),
 (427, 0.026315789473684213),
 (428, 0.055824219567359015),
 (429, 0.0),
 (430, 0.050669459193814),
 (431, 0.024182541670333724),
 (432, 0.11357771260606365),
 (433, 0.031219527052723135),
 (434, 0.0),
 (435, 0.03539961627023944),
 (436, 0.0),
 (437, 0.025649458802128853),
 (438, 0.12227899701112963),
 (439, 0.026315789473684213),
 (440, 0.024738534799764674),
 (441, 0.057353933467640436),
 (442, 0.04543108504242546),
 (443, 0.06390214842634574),
 (444, 0.0),
 (445, 0.0989541391990587),
 (446, 0.023174488732966077),
 (447, 0.06446025638903101),
 (448, 0.021300716142115247),
 (449, 0.10968169942141635),
 (450, 0.021300716142115247),
 (451, 0.025031308716087945),
 (452, 0.03065696697424829),
 (453, 0.024455799402225926),
 (454, 0.11707322644771176),
 (455, 0.060833032924035954),
 (456, 0.043355498476206004),
 (457, 0.08603090020146065),
 (458, 0.043355498476206004),
 (459, 0.03458572319330373),
 (460, 0.024182541670333724),
 (461, 0.1411956236812263),
 (462, 0.032283269414765066),
 (463, 0.03244428422615251),
 (464, 0.0),
 (465, 0.0),
 (466, 0.14509525002200233),
 (467, 0.10559715077387793),
 (468, 0.02782074420373286),
 (469, 0.05945550264670635),
 (470, 0.04543108504242546),
 (471, 0.06390214842634574),
 (472, 0.106676149412533),
 (473, 0.09269795493186431),
 (474, 0.0),
 (475, 0.043747863925980714),
 (476, 0.13530201829834768),
 (477, 0.0),
 (478, 0.05407380704358751),
 (479, 0.08797691788472335),
 (480, 0.0978231976089037),
 (481, 0.0),
 (482, 0.021873931962990357),
 (483, 0.12487810821089254),
 (484, 0.02913582733740325),
 (485, 0.052631578947368425),
 (486, 0.07992075789278003),
 (487, 0.12725695259515557),
 (488, 0.06657426652986062),
 (489, 0.0),
 (490, 0.14159846508095775),
 (491, 0.09909250441117726),
 (492, 0.076004188790721),
 (493, 0.03065696697424829),
 (494, 0.0),
 (495, 0.19088542889273336),
 (496, 0.0),
 (497, 0.0),
 (498, 0.06765100914917384),
 (499, 0.0),
 (500, 0.025976216673306556),
 (501, 0.08175191193132876),
 (502, 0.13369695534647594),
 (503, 0.07509392614826384),
 (504, 0.0),
 (505, 0.13530201829834768),
 (506, 0.03458572319330373),
 (507, 0.255608593705383),
 (508, 0.101338918387628),
 (509, 0.022075539284417398),
 (510, 0.0989541391990587),
 (511, 0.09197090092274487),
 (512, 0.02742042485535409),
 (513, 0.14843120879858804),
 (514, 0.04947706959952935),
 (515, 0.024738534799764674),
 (516, 0.028239124736245257),
 (517, 0.0),
 (518, 0.043747863925980714),
 (519, 0.0),
 (520, 0.0),
 (521, 0.025031308716087945),
 (522, 0.024182541670333724),
 (523, 0.04836508334066745),
 (524, 0.0),
 (525, 0.047324852428030105),
 (526, 0.028239124736245257),
 (527, 0.0331133089266261),
 (528, 0.022282825891079324),
 (529, 0.16742770563222897),
 (530, 0.05564148840746572),
 (531, 0.046348977465932154),
 (532, 0.021300716142115247),
 (533, 0.0602475233128778),
 (534, 0.0837707816583391),
 (535, 0.0978231976089037),
 (536, 0.1124803176664619),
 (537, 0.06765100914917384),
 (538, 0.0),
 (539, 0.2503866978335957),
 (540, 0.07509392614826384),
 (541, 0.10559715077387793),
 (542, 0.036973693332326786),
 (543, 0.07098727864204515),
 (544, 0.05564148840746572),
 (545, 0.024738534799764674),
 (546, 0.06362847629757779),
 (547, 0.08346223261119858),
 (548, 0.0),
 (549, 0.11959121830873498),
 (550, 0.024738534799764674),
 (551, 0.03771571432023571),
 (552, 0.0),
 (553, 0.028676966733820218),
 (554, 0.0),
 (555, 0.04499212706658475),
 (556, 0.02666903735313325),
 (557, 0.12227899701112963),
 (558, 0.0),
 (559, 0.0301237616564389),
 (560, 0.03604920469572501),
 (561, 0.03181423814878889),
 (562, 0.03065696697424829),
 (563, 0.025649458802128853),
 (564, 0.08885233166386385),
 (565, 0.043355498476206004),
 (566, 0.023918243661746996),
 (567, 0.025031308716087945),
 (568, 0.1411956236812263),
 (569, 0.047324852428030105),
 (570, 0.06765100914917384),
 (571, 0.04223886030955117),
 (572, 0.10743376064838502),
 (573, 0.0207703246198632),
 (574, 0.023414645289542353),
 (575, 0.04543108504242546),
 (576, 0.05195243334661311),
 (577, 0.1976738731537168),
 (578, 0.037463432463267755),
 (579, 0.14567913668701626),
 (580, 0.024182541670333724),
 (581, 0.14567913668701626),
 (582, 0.24511108480187255),
 (583, 0.03771571432023571),
 (584, 0.08111071056538127),
 (585, 0.024455799402225926),
 (586, 0.04499212706658476),
 (587, 0.09464970485606021),
 (588, 0.025649458802128853),
 (589, 0.1163350101494222),
 (590, 0.0301237616564389),
 (591, 0.06282808624375433),
 (592, 0.021119430154775586),
 (593, 0.0),
 (594, 0.04947706959952935),
 (595, 0.16059101370939324),
 (596, 0.09269795493186431),
 (597, 0.05923488777590923),
 (598, 0.03627381250550058),
 (599, 0.02742042485535409),
 (600, 0.06882472016116853),
 (601, 0.033463724070512735),
 (602, 0.09086217008485092),
 (603, 0.05407380704358751),
 (604, 0.0662266178532522),
 (605, 0.025031308716087945),
 (606, 0.0),
 (607, 0.05775642214923893),
 (608, 0.0),
 (609, 0.046829290579084706),
 (610, 0.058038100008800934),
 (611, 0.023174488732966077),
 (612, 0.06335829046432676),
 (613, 0.03539961627023944),
 (614, 0.04891159880445185),
 (615, 0.06131393394849658),
 (616, 0.03458572319330373),
 (617, 0.05006261743217589),
 (618, 0.08830215713766959),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06488856845230502),
 (622, 0.021119430154775586),
 (623, 0.0),
 (624, 0.1037571695799112),
 (625, 0.031219527052723135),
 (626, 0.08226127456606226),
 (627, 0.10882143751650175),
 (628, 0.0),
 (629, 0.04836508334066745),
 (630, 0.024455799402225926),
 (631, 0.050669459193814),
 (632, 0.07694837640638656),
 (633, 0.022282825891079324),
 (634, 0.07421560439929402),
 (635, 0.06622661785325219),
 (636, 0.023414645289542353),
 (637, 0.024182541670333724),
 (638, 0.03382550457458692),
 (639, 0.0),
 (640, 0.05990422978731538),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10012523486435178),
 (644, 0.05006261743217589),
 (645, 0.044151078568834795),
 (646, 0.052631578947368425),
 (647, 0.04836508334066745),
 (648, 0.0301237616564389),
 (649, 0.0),
 (650, 0.05195243334661311),
 (651, 0.0),
 (652, 0.042973504259354006),
 (653, 0.10882143751650175),
 (654, 0.10385162309931599),
 (655, 0.023918243661746996),
 (656, 0.0),
 (657, 0.03458572319330373),
 (658, 0.04836508334066745),
 (659, 0.025334729596907),
 (660, 0.09365858115816941),
 (661, 0.1675415633166782),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0602475233128778),
 (665, 0.06814662756363819),
 (666, 0.05006261743217589),
 (667, 0.0),
 (668, 0.13530201829834768),
 (669, 0.03539961627023944),
 (670, 0.01749278571353299),
 (671, 0.06814662756363819),
 (672, 0.028239124736245257),
 (673, 0.019968076595771794),
 (674, 0.07098727864204515),
 (675, 0.04499212706658476),
 (676, 0.028676966733820218),
 (677, 0.025031308716087945),
 (678, 0.116543309349613),
 (679, 0.0),
 (680, 0.07509392614826384),
 (681, 0.02742042485535409),
 (682, 0.019968076595771794),
 (683, 0.04836508334066745),
 (684, 0.0),
 (685, 0.03244428422615251),
 (686, 0.03181423814878889),
 (687, 0.10390486669322622),
 (688, 0.043355498476206004),
 (689, 0.0),
 (690, 0.025031308716087945),
 (691, 0.05923488777590923),
 (692, 0.10936965981495178),
 (693, 0.03382550457458692),
 (694, 0.021873931962990357),
 (695, 0.0662266178532522),
 (696, 0.021486752129677003),
 (697, 0.0),
 (698, 0.043355498476206004),
 (699, 0.03823595564509363),
 (700, 0.028676966733820218),
 (701, 0.057353933467640436),
 (702, 0.02249606353329238),
 (703, 0.021486752129677003),
 (704, 0.06814662756363819),
 (705, 0.024455799402225926),
 (706, 0.021677749238103002),
 (707, 0.0),
 (708, 0.024738534799764674),
 (709, 0.02060214108575823),
 (710, 0.05775642214923893),
 (711, 0.052631578947368425),
 (712, 0.0),
 (713, 0.024738534799764674),
 (714, 0.0),
 (715, 0.09933992677987831),
 (716, 0.027036903521793755),
 (717, 0.0),
 (718, 0.04499212706658476),
 (719, 0.0),
 (720, 0.026315789473684213),
 (721, 0.03244428422615251),
 (722, 0.0),
 (723, 0.024455799402225926),
 (724, 0.023662426214015053),
 (725, 0.0),
 (726, 0.0),
 (727, 0.030794751789719334),
 (728, 0.07254762501100118),
 (729, 0.04891159880445185),
 (730, 0.030254451040802585),
 (731, 0.05195243334661311),
 (732, 0.06814662756363819),
 (733, 0.061313933948496574),
 (734, 0.06684847767323797),
 (735, 0.06684847767323797),
 (736, 0.029617443887954616),
 (737, 0.07694837640638656),
 (738, 0.0),
 (739, 0.03823595564509363),

In [81]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0000000000000002),
 (1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3728, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.2503866978335957),
 (582, 0.24511108480187255),
 (1202, 0.24455799402225925),
 (1192, 0.2367785320221084),
 (61, 0.23179316248638274),
 (778, 0.23174488732966075),
 (4046, 0.2278389747471728),
 (1916, 0.22528177844479153),
 (2782, 0.21853668936906193),
 (172, 0.21239769762143662),
 (972, 0.2108663315950723),
 (322, 0.2105263157894737),
 (2329, 0.20443988269091456),
 (3606, 0.20437977982832192),
 (260, 0.20395079136182276),
 (151, 0.2029530274475215),
 (4190, 0.2029530274475215),
 (1440, 0.20277677641345318),
 (74, 0.20246457179963143),
 (1087, 0.2020475485519274),
 (3671, 0.1979082783981174),
 (973, 0.19767387315371682),
 (577, 0.1976738731537168),
 (47, 0.19672236884115843),
 (2969, 0.19252140716412977),
 (942, 0.19134594929397597),
 (495, 0.19088542889273336),
 (1199, 0.19088542889273336),
 (305, 0.1900748713929803),
 (4, 0.18929940971212042),
 (4405, 0.18731716231633883),
 (94, 0.1873171623163388),
 (27, 0.18693292157876878),
 (3325, 0.1860807318911967),
 (1273, 0.18394180184548975),
 (1327, 0.18394180184548975),
 (2997, 0.1813690625275029),
 (3997, 0.18074256993863339),
 (83, 0.17996850826633903),
 (1069, 0.17954621161490197),
 (220, 0.1777046633277277),
 (184, 0.177343107178349),
 (1319, 0.17699808135119718),
 (168, 0.17521916101261562),
 (2200, 0.17521916101261562),
 (4336, 0.17521916101261562),
 (931, 0.1748149640244195),
 (36, 0.17316974359835272),
 (373, 0.17292861596651865),
 (300, 0.1711905958155815),
 (3536, 0.1711905958155815),
 (3160, 0.17040572913692198),
 (1978, 0.16943474841747153),
 (661, 0.1675415633166782),
 (529, 0.16742770563222897),
 (1827, 0.16742770563222897),
 (91, 0.16692446522239718),
 (41, 0.16563698349810535),
 (67, 0.16452254913212452),
 (150, 0.16426202236672155),
 (1533, 0.16222142113076254),
 (342, 0.16122923187750418),
 (595, 0.16059101370939324),
 (31, 0.15907119074394446),
 (2511, 0.15907119074394446),
 (1176, 0.15789473684210528),
 (4008, 0.15737789507292674),
 (2727, 0.15609763526361567),
 (149, 0.15511334686589626),
 (838, 0.1540171257313038),
 (26, 0.15389675281277312),
 (187, 0.15389675281277312),
 (1379, 0.152008377581442),
 (111, 0.15018785229652767),
 (1342, 0.15018785229652767),
 (311, 0.15018785229652765),
 (52, 0.14843120879858804),
 (513, 0.14843120879858804),
 (2071, 0.14808721943977307),
 (7, 0.14673479641335554),
 (2756, 0.14659886790209342),
 (127, 0.14601068654819693),
 (579, 0.14567913668701626),
 (581, 0.14567913668701626),
 (108, 0.14509525002200235),
 (1295, 0.14509525002200235),
 (466, 0.14509525002200233),
 (1392, 0.14421498760030763),
 (1475, 0.14421498760030763),
 (1353, 0.14350946197048198),
 (1934, 0.14350946197048198),
 (275, 0.1433848336691011),
 (294, 0.1433848336691011),
 (3352, 0.1433848336691011),
 (1054, 0.1419745572840903),
 (1271, 0.1419745572840903),
 (490, 0.14159846508095775),
 (1484, 0.14159846508095775),
 (413, 0.1411956236812263),
 (461, 0.1411956236812263),
 (568, 0.1411956236812263),
 (2492, 0.1411956236812263),
 (95, 0.1404878717372541),
 (17, 0.13977653617040256),
 (46, 0.1391037210186643),
 (3407, 0.1391037210186643),
 (1961, 0.13872950617564817),
 (56, 0.13834289277321493),
 (249, 0.13834289277321493),
 (1325, 0.13834289277321493),
 (3779, 0.13834289277321493),
 (72, 0.13710212427677043),
 (843, 0.13710212427677043),
 (859, 0.13710212427677043),
 (2165, 0.13710212427677043),
 (4538, 0.13629325512727639),
 (476, 0.13530201829834768),
 (505, 0.13530201829834768),
 (668, 0.13530201829834768),
 (935, 0.13530201829834768),
 (3980, 0.13530201829834768),
 (1804, 0.13518451760896877),
 (4348, 0.13497638119975428),
 (1320, 0.13476498501489081),
 (158, 0.13369695534647594),
 (502, 0.13369695534647594),
 (777, 0.13369695534647594),
 (126, 0.13334518676566626),
 (1556, 0.13334518676566626),
 (1369, 0.1324532357065044),
 (2374, 0.1324532357065044),
 (2580, 0.1324532357065044),
 (4077, 0.13157894736842107),
 (2129, 0.13124359177794215),
 (1013, 0.12988108336653278),
 (2177, 0.12988108336653278),
 (3620, 0.12988108336653278),
 (134, 0.12977713690461004),
 (368, 0.12977713690461004),
 (1770, 0.12977713690461004),
 (2869, 0.12892051277806202),
 (14, 0.12824729401064427),
 (138, 0.12824729401064427),
 (369, 0.12824729401064427),
 (1084, 0.12824729401064427),
 (2682, 0.12824729401064427),
 (4228, 0.12824729401064427),
 (487, 0.12725695259515557),
 (773, 0.12725695259515557),
 (2968, 0.12725695259515557),
 (937, 0.126673647984535),
 (1737, 0.12565617248750865),
 (2476, 0.12565617248750865),
 (166, 0.12515654358043973),
 (754, 0.12515654358043973),
 (2446, 0.12515654358043973),
 (3626, 0.12515654358043973),
 (483, 0.12487810821089254),
 (1094, 0.12487810821089254),
 (1156, 0.12487810821089254),
 (2648, 0.12487810821089254),
 (102, 0.12462194771917919),
 (84, 0.12361284651454937),
 (208, 0.12262786789699316),
 (3374, 0.12262786789699316),
 (1874, 0.12262786789699315),
 (438, 0.12227899701112963),
 (557, 0.12227899701112963),
 (1297, 0.12227899701112963),
 (2327, 0.12166606584807191),
 (2670, 0.12166606584807191),
 (3081, 0.12166606584807191),
 (139, 0.12072654548783007),
 (68, 0.1204950466257556),
 (781, 0.1204950466257556),
 (1002, 0.1204950466257556),
 (1272, 0.1204950466257556),
 (1654, 0.1204950466257556),
 (1000, 0.11980845957463077),
 (549, 0.11959121830873498),
 (870, 0.11959121830873498),
 (900, 0.11959121830873498),
 (3233, 0.11959121830873498),
 (1045, 0.11846977555181847),
 (1829, 0.11846977555181847),
 (2056, 0.11846977555181847),
 (2737, 0.11846977555181847),
 (4673, 0.11846977555181847),
 (1711, 0.11803342130469506),
 (3719, 0.11803342130469506),
 (1669, 0.11803342130469505),
 (2785, 0.11803342130469505),
 (3998, 0.11803342130469505),
 (160, 0.11712303424679457),
 (182, 0.11707322644771176),
 (278, 0.11707322644771176),
 (454, 0.11707322644771176),
 (1613, 0.11707322644771176),
 (2280, 0.11707322644771176),
 (28, 0.116543309349613),
 (122, 0.116543309349613),
 (422, 0.116543309349613),
 (678, 0.116543309349613),
 (589, 0.1163350101494222),
 (2543, 0.11587244366483038),
 (1493, 0.11551284429847784),
 (3210, 0.11506355109724453),
 (189, 0.1147078669352809),
 (1218, 0.11470786693528089),
 (236, 0.11470786693528087),
 (1299, 0.11470786693528087),
 (85, 0.11412706387705432),
 (432, 0.11357771260606365),
 (1414, 0.11357771260606365),
 (50, 0.11295649894498103),
 (1612, 0.11295649894498103),
 (123, 0.1124803176664619),
 (420, 0.1124803176664619),
 (536, 0.1124803176664619),
 (889, 0.11243619908556624),
 (3145, 0.11239029738980327),
 (256, 0.11164843913471803),
 (808, 0.11164843913471803),
 (1346, 0.11164843913471803),
 (1571, 0.11164843913471803),
 (2368, 0.11141412945539662),
 (1508, 0.11141412945539661),
 (3307, 0.11141412945539661),
 (87, 0.11128297681493143),
 (121, 0.11128297681493143),
 (232, 0.11128297681493143),
 (4468, 0.11128297681493143),
 (206, 0.11092107999698035),
 (238, 0.11092107999698035),
 (228, 0.11037769642208699),
 (81, 0.11020775375559676),
 (1570, 0.11020775375559674),
 (3426, 0.10968169942141637),
 (21, 0.10968169942141635),
 (449, 0.10968169942141635),
 (1029, 0.10968169942141635),
 (1941, 0.10968169942141635),
 (2144, 0.10968169942141635),
 (3006, 0.10968169942141635),
 (692, 0.10936965981495178),
 (200, 0.10882143751650175),
 (627, 0.10882143751650175),
 (653, 0.10882143751650175),
 (1520, 0.10882143751650175),
 (307, 0.10876595882948199),
 (5, 0.10838874619051501),
 (3091, 0.10838874619051501),
 (3628, 0.10838874619051501),
 (740, 0.108388746190515),
 (786, 0.10814761408717502),
 (3496, 0.10814761408717502),
 (4777, 0.10814761408717502),
 (229, 0.1074861545850028),
 (572, 0.10743376064838502),
 (939, 0.1068366854693644),
 (332, 0.106676149412533),
 (472, 0.106676149412533),
 (1235, 0.106676149412533),
 (170, 0.10650358071057624),
 (262, 0.10650358071057624),
 (1164, 0.10619884881071831),
 (1497, 0.10619884881071831),
 (1741, 0.10619884881071831),
 (2157, 0.10619884881071831),
 (2630, 0.10619884881071831),
 (4133, 0.10619884881071831),
 (467, 0.10559715077387793),
 (541, 0.10559715077387793),
 (1492, 0.10559715077387793),
 (131, 0.10526315789473685),
 (295, 0.10526315789473685),
 (2068, 0.10526315789473685),
 (3338, 0.10526315789473685),
 (2494, 0.10471347707292387),
 (75, 0.10390486669322622),
 (223, 0.10390486669322622),
 (687, 0.10390486669322622),
 (814, 0.10390486669322622),
 (1193, 0.10390486669322622),
 (1767, 0.10390486669322622),
 (2813, 0.10390486669322622),
 (2435, 0.103851623099316),
 (654, 0.10385162309931599),
 (105, 0.1037571695799112),
 (233, 0.1037571695799112),
 (624, 0.1037571695799112),
 (2319, 0.1037571695799112),
 (2452, 0.1037571695799112),
 (2517, 0.1037571695799112),
 (3053, 0.1037571695799112),
 (3619, 0.1037571695799112),
 (3837, 0.1037571695799112),
 (1451, 0.10301070542879115),
 (10, 0.10259783520851541),
 (1080, 0.10259783520851541),
 (3150, 0.10259783520851541),
 (3632, 0.10259783520851541),
 (3753, 0.10259783520851541),
 (3872, 0.10259783520851541),
 (4095, 0.10259783520851541),
 (2102, 0.10218988991416095),
 (2758, 0.10147651372376076),
 (3659, 0.10147651372376076),
 (3952, 0.10147651372376076),
 (3439, 0.10138838820672659),
 (508, 0.101338918387628),
 (1292, 0.101338918387628),
 (2243, 0.10133891838762799),
 (1401, 0.10060545457319173),
 (1435, 0.10060545457319173),
 (2095, 0.10060545457319173),
 (312, 0.10012523486435178),
 (330, 0.10012523486435178),
 (643, 0.10012523486435178),
 (986, 0.10012523486435178),
 (1035, 0.10012523486435178),
 (1610, 0.10012523486435178),
 (35, 0.09933992677987831),
 (157, 0.09933992677987831),
 (319, 0.09933992677987831),
 (325, 0.09933992677987831),
 (715, 0.09933992677987831),
 (1075, 0.09933992677987831),
 (1278, 0.09933992677987831),
 (1880, 0.09933992677987831),
 (2049, 0.09933992677987831),
 (4016, 0.09933992677987831),
 (4196, 0.09933992677987831),
 (4490, 0.09933992677987831),
 (363, 0.09909250441117726),
 (491, 0.09909250441117726),
 (266, 0.0989541391990587),
 (445, 0.0989541391990587),
 (510, 0.0989541391990587),
 (3618, 0.0989541391990587),
 (3781, 0.0989541391990587),
 (3933, 0.0989541391990587),
 (1771, 0.09836118442057921),
 (410, 0.0978231976089037),
 (480, 0.0978231976089037),
 (535, 0.0978231976089037),
 (898, 0.0978231976089037),
 (1107, 0.0978231976089037),
 (1397, 0.0978231976089037),
 (1819, 0.0978231976089037),
 (2249, 0.0978231976089037),
 (33, 0.09733285267845754),
 (148, 0.09733285267845754),
 (263, 0.09733285267845754),
 (878, 0.09733285267845754),
 (1154, 0.09733285267845754),
 (1723, 0.09733285267845754),
 (1938, 0.09733285267845754),
 (2783, 0.09733285267845754),
 (4254, 0.09733285267845754),
 (4403, 0.09733285267845754),
 (4472, 0.09733285267845754),
 (9, 0.0967301666813349),
 (334, 0.0967301666813349),
 (371, 0.09567297464698798),
 (412, 0.09567297464698798),
 (2237, 0.09567297464698798),
 (2552, 0.09567297464698798),
 (4545, 0.09558988911273408),
 (362, 0.09544271444636668),
 (791, 0.09544271444636668),
 (1569, 0.09544271444636668),
 (2558, 0.09544271444636668),
 (4201, 0.09544271444636668),
 (18, 0.09493290614465533),
 (11, 0.09464970485606021),
 (587, 0.09464970485606021),
 (660, 0.09365858115816941),
 (920, 0.09365858115816941),
 (978, 0.09365858115816941),
 (1274, 0.09365858115816941),
 (1355, 0.09365858115816941),
 (1470, 0.09365858115816941),
 (1682, 0.09365858115816941),
 (1688, 0.09365858115816941),
 (1717, 0.09365858115816941),
 (2392, 0.09365858115816941),
 (2484, 0.09365858115816941),
 (2588, 0.09365858115816941),
 (2641, 0.09365858115816941),
 (2646, 0.09365858115816941),
 (2816, 0.09365858115816941),
 (3535, 0.09365858115816941),
 (3718, 0.09365858115816941),
 (4331, 0.09365858115816941),
 (4502, 0.09365858115816941),
 (301, 0.09365858115816939),
 (129, 0.09269795493186431),
 (243, 0.09269795493186431),
 (279, 0.09269795493186431),
 (473, 0.09269795493186431),
 (596, 0.09269795493186431),
 (813, 0.09269795493186431),
 (1442, 0.09269795493186431),
 (1697, 0.09269795493186431),
 (3405, 0.09269795493186431),
 (785, 0.09243423333081695),
 (219, 0.09197090092274487),
 (244, 0.09197090092274487),
 (511, 0.09197090092274487),
 (1752, 0.09197090092274487),
 (2089, 0.09197090092274487),
 (2647, 0.09197090092274487),
 (3734, 0.09197090092274487),
 (230, 0.09183979479633063),
 (799, 0.09183979479633063),
 (239, 0.09125667909262308),
 (2566, 0.09125667909262308),
 (43, 0.09086217008485092),
 (602, 0.09086217008485092),
 (995, 0.09086217008485092),
 (1231, 0.09086217008485092),
 (1842, 0.09086217008485092),
 (3879, 0.09086217008485092),
 (12, 0.09037128496931669),
 (88, 0.09037128496931669),
 (167, 0.09037128496931669),
 (356, 0.09037128496931669),
 (400, 0.09037128496931669),
 (1304, 0.09037128496931669),
 (1476, 0.09037128496931669),
 (2247, 0.09037128496931669),
 (2955, 0.09037128496931669),
 (331, 0.08998425413316952),
 (2359, 0.08998425413316952),
 (2792, 0.08998425413316952),
 (2852, 0.08998425413316952),
 (3387, 0.08998425413316952),
 (3441, 0.08998425413316952),
 (3460, 0.08998425413316952),
 (4343, 0.08998425413316952),
 (4353, 0.08998425413316952),
 (274, 0.08977310580745099),
 (1902, 0.0891313035643173),
 (2111, 0.08903057122447033),
 (292, 0.08885233166386385),
 (564, 0.08885233166386385),
 (1025, 0.08885233166386385),
 (2656, 0.08885233166386385),
 (2864, 0.08885233166386385),
 (3320, 0.08885233166386385),
 (169, 0.08830215713766959),
 (270, 0.08830215713766959),
 (618, 0.08830215713766959),
 (1779, 0.08830215713766959),
 (2105, 0.08830215713766959),
 (2709, 0.08830215713766959),
 (2736, 0.08830215713766959),
 (3551, 0.08830215713766959),
 (479, 0.08797691788472335),
 (752, 0.08749572785196143),
 (1828, 0.08749572785196143),
 (2444, 0.08746392856766495),
 (23, 0.08740748201220976),
 (141, 0.08740748201220976),
 (389, 0.08740748201220976),
 (745, 0.08740748201220976),
 (794, 0.08740748201220976),
 (960, 0.08740748201220976),
 (1247, 0.08740748201220976),
 (1257, 0.08740748201220976),
 (3446, 0.08740748201220976),
 (3447, 0.08740748201220976),
 (143, 0.08671099695241201),
 (199, 0.08671099695241201),
 (827, 0.08671099695241201),
 (1526, 0.08671099695241201),
 (2876, 0.08671099695241201),
 (3554, 0.08671099695241201),
 (4516, 0.08671099695241201),
 (4587, 0.08671099695241201),
 (2, 0.08603090020146065),
 (457, 0.08603090020146065),
 (775, 0.08603090020146065),
 (1374, 0.08603090020146065),
 (2579, 0.08603090020146065),
 (3133, 0.08603090020146065),
 (4754, 0.08603090020146065),
 (234, 0.08594700851870801),
 (1017, 0.08594700851870801),
 (2350, 0.08594700851870801),
 (32, 0.08520286456846099),
 (217, 0.08520286456846099),
 (142, 0.08471737420873576),
 (894, 0.08471737420873576),
 (1095, 0.08471737420873576),
 (1140, 0.08471737420873576),
 (1585, 0.08471737420873576),
 (2300, 0.08471737420873576),
 (4560, 0.08471737420873576),
 (48, 0.08447772061910234),
 (190, 0.08447772061910234),
 (1303, 0.08447772061910234),
 (1635, 0.08447772061910234),
 (2966, 0.08447772061910234),
 (62, 0.0837707816583391),
 (381, 0.0837707816583391),
 (534, 0.0837707816583391),
 (1694, 0.0837707816583391),
 (3178, 0.0837707816583391),
 (3216, 0.0837707816583391),
 (3976, 0.0837707816583391),
 (4737, 0.0837707816583391),
 (1, 0.08346223261119858),
 (152, 0.08346223261119858),
 (203, 0.08346223261119858),
 (315, 0.08346223261119858),
 (547, 0.08346223261119858),
 (1684, 0.08346223261119858),
 (2124, 0.08346223261119858),
 (2382, 0.08321783316232578),
 (19, 0.0830812984794528),
 (403, 0.0830812984794528),
 (3903, 0.0830812984794528),
 (45, 0.08240856434303293),
 (2199, 0.08240856434303293),
 (39, 0.08226127456606226),
 (227, 0.08226127456606226),
 (341, 0.08226127456606226),
 (626, 0.08226127456606226),
 (787, 0.08226127456606226),
 (1205, 0.08226127456606226),
 (1745, 0.08226127456606226),
 (2163, 0.08226127456606226),
 (2657, 0.08226127456606226),
 (3138, 0.08226127456606226),
 (3299, 0.08226127456606226),
 (3468, 0.08226127456606226),
 (63, 0.08175191193132876),
 (501, 0.08175191193132876),
 (38, 0.08111071056538127),
 (242, 0.08111071056538127),
 (245, 0.08111071056538127),
 (306, 0.08111071056538127),
 (584, 0.08111071056538127),
 (812, 0.08111071056538127),
 (866, 0.08111071056538127),
 (901, 0.08111071056538127),
 (1267, 0.08111071056538127),
 (1515, 0.08111071056538127),
 (1660, 0.08111071056538127),
 (2335, 0.08111071056538127),
 (2640, 0.08111071056538127),
 (2667, 0.08111071056538127),
 (2861, 0.08111071056538127),
 (2873, 0.08111071056538127),
 (3525, 0.08111071056538127),
 (3924, 0.08111071056538127),
 (4492, 0.08111071056538127),
 (4568, 0.08111071056538127),
 (4626, 0.08111071056538127),
 (4641, 0.08111071056538127),
 (4654, 0.08111071056538127),
 (4657, 0.08111071056538127),
 (51, 0.08048436365855338),
 (164, 0.08000711205939975),
 (854, 0.08000711205939975),
 (899, 0.08000711205939975),
 (1323, 0.08000711205939975),
 (1743, 0.08000711205939975),
 (2679, 0.08000711205939975),
 (3762, 0.08000711205939975),
 (3814, 0.08000711205939975),
 (3849, 0.08000711205939975),
 (486, 0.07992075789278003),
 (103, 0.07987230638308718),
 (222, 0.07987230638308718),
 (1530, 0.07987230638308718),
 (2788, 0.07987230638308718),
 (4506, 0.07987230638308718),
 (1894, 0.0792740035289418),
 (16, 0.07894736842105264),
 (37, 0.07894736842105264),
 (241, 0.07894736842105264),
 (329, 0.07894736842105264),
 (1078, 0.07894736842105264),
 (1159, 0.07894736842105264),
 (2291, 0.07894736842105264),
 (3231, 0.07894736842105264),
 (4316, 0.07894736842105264),
 (193, 0.07878168645790681),
 (153, 0.07868894753646337),
 (776, 0.07868894753646337),
 (1043, 0.07868894753646337),
 (1824, 0.07868894753646337),
 (1922, 0.07868894753646337),
 (3726, 0.07868894753646337),
 (3830, 0.07868894753646337),
 (4279, 0.07868894753646337),
 (4473, 0.07868894753646337),
 (125, 0.07843304784240032),
 (286, 0.0781166566864507),
 (1655, 0.0781166566864507),
 (174, 0.07792865001991967),
 (402, 0.07792865001991967),
 (922, 0.07792865001991967),
 (1111, 0.07792865001991967),
 (2936, 0.07792865001991967),
 (3026, 0.07792865001991967),
 (3089, 0.07792865001991967),
 (3100, 0.07792865001991967),
 (3162, 0.07792865001991967),
 (4341, 0.07792865001991967),
 (1920, 0.07755667343294813),
 (3558, 0.07755667343294813),
 (1280, 0.0770085628656519),
 (40, 0.07694837640638656),
 (96, 0.07694837640638656),
 (101, 0.07694837640638656),
 (112, 0.07694837640638656),
 (207, 0.07694837640638656),
 (632, 0.07694837640638656),
 (737, 0.07694837640638656),
 (1287, 0.07694837640638656),
 (2215, 0.07694837640638656),
 (4266, 0.07694837640638656),
 (4624, 0.07694837640638656),
 (850, 0.07647191129018727),
 (1003, 0.07647191129018727),
 (1137, 0.07647191129018727),
 (1252, 0.07647191129018727),
 (1617, 0.07647191129018727),
 (2161, 0.07647191129018727),
 (2270, 0.07647191129018727),
 (2708, 0.07647191129018727),
 (3428, 0.07647191129018727),
 (4163, 0.07647191129018727),
 (70, 0.076004188790721),
 (82, 0.076004188790721),
 (235, 0.076004188790721),
 (349, 0.076004188790721),
 (492, 0.076004188790721),
 (1288, 0.076004188790721),
 (1519, 0.076004188790721),
 (2445, 0.076004188790721),
 (2914, 0.076004188790721),
 (4558, 0.076004188790721),
 (246, 0.07594632491572426),
 (2001, 0.07543142864047142),
 (3329, 0.07530940414109724),
 (98, 0.07509392614826384),
 (210, 0.07509392614826384),
 (361, 0.07509392614826384),
 (365, 0.07509392614826384),
 (503, 0.07509392614826384),
 (540, 0.07509392614826384),
 (680, 0.07509392614826384),
 (1007, 0.07509392614826384),
 (1291, 0.07509392614826384),
 (2159, 0.07509392614826384),
 (4043, 0.07509392614826384),
 (4203, 0.07509392614826384),
 (2252, 0.07492686492653551),
 (205, 0.07443229275647868),
 (800, 0.07443229275647868),
 (993, 0.07443229275647868),
 (1321, 0.07443229275647868),
 (1517, 0.07443229275647868),
 (1766, 0.07443229275647868),
 (2322, 0.07443229275647868),
 (2547, 0.07443229275647868),
 (2797, 0.07443229275647868),
 (3067, 0.07443229275647868),
 (3115, 0.07443229275647868),
 (3124, 0.07443229275647868),
 (4009, 0.07443229275647868),
 (4412, 0.07443229275647868),
 (4542, 0.07443229275647868),

In [82]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6] # extract the top 5 similar

[(1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3728, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.2503866978335957)]

In [75]:
# to extract the indx of the movie
new_df[new_df['title']=='Avatar'].index

Index([0], dtype='int64')

In [76]:
new_df[new_df['title']=='Avatar'].index[0]

0

In [77]:
new_df[new_df['title']=='Batman Begins'].index[0]

119

In [96]:
 # if a movie is given then return 5 similar movies lyk the given movie
def recommend(movie):
    try:
        # Find the index of the movie in the DataFrame
        movie_index = new_df[new_df['title'] == movie].index[0]
        
        # Get the pairwise similarity scores for this movie
        distances = similarity[movie_index]
        
        # Get the indices of the top 5 similar movies (excluding the movie itself)
        movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
        
        # Return the titles of the similar movies
        return [new_df.iloc[i[0]].title for i in movies_list]
    
    except IndexError:
        return f"Movie '{movie}' not found."
    except Exception as e:
        return str(e)

In [97]:
recommend('Avatar')

['Aliens vs Predator: Requiem',
 'Aliens',
 'Falcon Rising',
 'Independence Day',
 'Titan A.E.']

In [98]:
import gradio as gr

# Gradio function wrapper
def gradio_recommend(movie):
    # Get the list of similar movies
    similar_movies = recommend(movie)
    
    # Join the list into a single string with new lines
    if isinstance(similar_movies, list):
        return "\n".join(similar_movies)
    else:
        return similar_movies  # In case of error message

# Define Gradio inputs and outputs
inputs = gr.Textbox(label="Movie Title")
outputs = gr.Textbox(label="Recommended Movies")

# Create Gradio interface
interface = gr.Interface(
    fn=gradio_recommend,
    inputs=inputs,
    outputs=outputs,
    title="Movie Recommendation System",
    description="Enter a movie title and get the top 5 similar movies."
)

# Launch Gradio interface
interface.launch()

Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.

IMPORTANT: You are using gradio version 3.43.1, however version 4.29.0 is available, please upgrade.
--------